import {Color} from "./colors";
import {COLOR_REGEXP} from "../../adapters/converter";
import {OneNote} from "../onenote";
import {round3} from "../../rnote/utils";


// Original idea: https://www.youtube.com/watch?v=kuGA8a_W4s4
function* splitWrappedText(text: HTMLElement) {
    const range = document.createRange();
    let lastIndex = 0;
    const textContent = text.textContent || "";
    for (let i = 0; i < textContent.length; i++) {
        range.setStart(text, lastIndex);
        range.setEnd(text, i + 1);
        if (range.getClientRects().length > 1) {
            yield textContent.substring(lastIndex, i);
            lastIndex = i;
        }
    }
    if (lastIndex != textContent.length) {
        yield textContent.substring(lastIndex, textContent.length);
    }
}

export interface Chunk {
    index: number,
    line: string,
    x: number,
    y: number,
    width: number
    height: number
}

export class Text {
    readonly document: OneNote;
    readonly text: HTMLSpanElement;
    readonly x: number;
    readonly y: number;
    readonly width: number;
    readonly height: number;
    readonly color: Color;
    readonly fontSize: number;
    readonly #fontFamily: string;

    constructor(document: OneNote, text: HTMLSpanElement) {
        this.document = document;
        this.text = text;
        const color_property = window.getComputedStyle(text).getPropertyValue("color");
        let [_, r, g, b] = ["", "0", "0", "0"];
        try {
            [_, r, g, b] = color_property.match(COLOR_REGEXP) || ["", "0", "0", "0"];
        } catch (e) {
            console.debug(`NEX: error while matching color from ${color_property}`, e);
        }
        this.color = new Color(Number(r), Number(g), Number(b), 1, document.options.texts_dark_mode);
        // TODO: add the possibility to override export font
        this.#fontFamily = getComputedStyle(text).getPropertyValue("font-family");


        this.fontSize = ((Number(window.getComputedStyle(text).getPropertyValue("font-size").replace("px", "")) ?? 12));
        const offsets = this.document.offsets;
        const zoom = this.document.zoom;
        const box = this.text.getBoundingClientRect();
        this.x = round3((box.x - offsets.x) / zoom);
        this.y = round3((box.y - offsets.y) / zoom);
        this.width = round3(box.width);
        this.height = round3(box.height);
    }

    get font() {
        return (this.#fontFamily.split(", ")[1] ?? "Calibri").trim();
    }

    get fontFamily(): string | undefined {
        return this.#fontFamily.split(", ")[2].trim();
    }

    // In a previous version this iterated over chunks of text generated by OneNote, caused by typos
    // (es: <span class="SpellingError">...</span>). This wasn't necessary at all, and it was causing the add-on to
    // export the text into chunks unnecessarily.
    // Now this is a single-element generator. This is to maintain the compatibility with the existing code.
    // TODO: remove this function and the corresponding code in the converters. This wrap is unneccessary.
    * chunks(): Generator<Chunk> {
        if (!this.text.children) return;
        for (let child of this.text.children) {
            // const htmlChild = child as HTMLElement;
            const nodeTextChild = child.firstChild as (HTMLElement | null);
            if (nodeTextChild) {
                const lines = splitWrappedText(nodeTextChild);

                const offsets = this.document.offsets;
                const zoom = this.document.zoom;

                const textBoundaries = child.getClientRects();
                let index = 0;
                for (const line of lines) {
                    const rect = textBoundaries[index];

                    const x = round3((rect.x - offsets.x) / zoom);
                    const y = round3((rect.y - offsets.y) / zoom);

                    const width = round3(rect.width / zoom);
                    yield {index: index++, line, x, y, width, height: round3(rect.height)};
                }
            }

        }
    }
}